<?php $cssurl =  str_replace('index.php/','',$this->getUrl());?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/generic-nav.css'; ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/grid12.css'; ?>" media="all">
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery-1.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery-noconflict.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery_004.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery_003.js'; ?>"></script> 

 
