<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mksslider/css/font-awesome.min.css'); ?>">
 
</head>
<body>
 
  <div class="container">
    <div id="slides">
<?php 
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$sql = $connection->query("select * from mksresponsivebannerslider");
while($row1 = $sql->fetch())
{
$title = $row1["title"];
$urlx = $row1["image"]; 
$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imgurl=$media_url.$urlx;
?>
<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>">
<?php } ?>     
</div>
</div>
 
<script src="<?php echo $this->getSkinUrl('mksslider/js/jquery-1.9.1.min.js'); ?>"></script>
<script src="<?php echo $this->getSkinUrl('mksslider/js/jquery.slides.min.js'); ?>"></script>
<script>
    $(function() {
      $('#slides').slidesjs({
        width: 800,
        height: 300,
        play: {
          active: true,
          auto: true,
          interval: 4000,
          swap: true
        }
      });
    });
  </script>
 
 
